config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  resources :attendances
  resources :venues

  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :user
  belongs_to :production
  belongs_to :venue

  accepts_nested_attributes_for :production
end

app/models/production.rb
class Production < ApplicationRecord
  belongs_to :show

  has_many :attendances
  has_many :users, through: :attendances

  accepts_nested_attributes_for :show
end

app/models/show.rb
class Show < ApplicationRecord
    has_many :productions
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :attendances
  has_many :productions, through: :attendances
end

app/models/venue.rb
class Venue < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def after_sign_in_path_for(resource)
    user_path(resource)
  end
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  def create
    attendance = Attendance.new
    attendance.build_production
    attendance.assign_attributes(attendance_params)
    attendance.production.build_show(title: attendance.production.title)
    attendance.save!

    redirect_to attendance.user
  end

  private

  def attendance_params
    params.require(:attendance)
          .permit(:user_id, :venue_id, :date, :notes, production_attributes: [:title])
  end
end

app/controllers/productions_controller.rb
class AttendancesController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id]) 
    @attendance = Attendance.new
    @attendance.user = @user
    @attendance.build_production
  end
end

app/controllers/venues_controller.rb
class VenuesController < ApplicationController

  def new
    @venue = Venue.new
  end


  def create
    @venue = Venue.new
    @venue.assign_attributes(venue_params)
    @venue.save!

    redirect_to venues_path
  end
 
  private

  def venue_params
    params.require(:venue).permit(:name)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Showlist</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <div>
    <% if user_signed_in? %>
      <%= link_to('Logout', destroy_user_session_path, method: :delete) %>        
    <% else %>
      <%= link_to('Login', new_user_session_path)  %>
    <% end %>
    </div>
    
    <%= yield %>
  </body>
</html>

app/views/users/show.html.erb
<h1>Your list</h1>

<% if current_user.attendances.empty? %>
  <div>Nothing in your list.</div>
<% else %>
  <table>

  <thead>
    <tr>
      <td>Title</td>
      <td>Venue</td>
      <td>Date</td>
      <td>Notes</td>
    </tr>
  </thead>
  <tbody>
    <% current_user.attendances.each do |attendance| %>
      <tr>
        <td><%= attendance.production.title%></td> 
        <td><%= attendance.venue.name if attendance.venue.present? %></td> 
        <td><%= attendance.date.strftime("%B %d, %Y") %></td>
        <td><%= attendance.notes %></td>
      </tr>
    <% end %>
  </tbody>
  </table>
<% end %>

<h2>Add to your list!</h2>

<%= form_for @attendance do |f| %>
  <%= f.hidden_field :user_id, value: @attendance.user_id %>

  <%= f.fields_for :production do |production_form| %>
    <p>
      <%= production_form.label :title %>
      <%= production_form.text_field :title %>
    </p>

    
  <% end %>

  <p>
    <%= f.label :venue %>
    <%= f.select :venue_id, options_from_collection_for_select(Venue.all, :id, :name) %>
  </p>

  Don't see the venue? <%= link_to 'Add a venue', new_venue_path %>.

  <p>
    <%= f.label :notes %>
    <%= f.text_area :notes %>
  </p>

  <p>
    <%= f.label :date %>
    <%= f.date_field :date %>
  </p>

   <p>
    <%= f.submit 'Add!' %>
  </p>
<% end %>

app/views/venues/index.html.erb
<%= link_to "Back to your list", user_path(current_user) %>
<h2>Venues</h2>

<ul>
  <% Venue.all.each do |venue| %>
  <li><%= venue.name %></li>
  <% end %>
</ul>

app/views/venues/new.html.erb
<%= link_to "Back to your list", user_path(current_user) %>
<h2>Add a venue!</h2>

<%= form_for @venue do |f| %>
  <p>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.submit 'Add!' %>
  </p>
<% end %>

app/views/welcome/index.html.erb
whee! making a show list app.